// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	network.proto

It has these top-level messages:
	MsgReq
	MsgRes
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgReq_MsgType int32

const (
	MsgReq_UNDEFINED MsgReq_MsgType = 0
	MsgReq_GETBLOCK  MsgReq_MsgType = 1
)

var MsgReq_MsgType_name = map[int32]string{
	0: "UNDEFINED",
	1: "GETBLOCK",
}
var MsgReq_MsgType_value = map[string]int32{
	"UNDEFINED": 0,
	"GETBLOCK":  1,
}

func (x MsgReq_MsgType) String() string {
	return proto1.EnumName(MsgReq_MsgType_name, int32(x))
}
func (MsgReq_MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type MsgReq struct {
	Msg []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *MsgReq) Reset()                    { *m = MsgReq{} }
func (m *MsgReq) String() string            { return proto1.CompactTextString(m) }
func (*MsgReq) ProtoMessage()               {}
func (*MsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MsgRes struct {
	Msg []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *MsgRes) Reset()                    { *m = MsgRes{} }
func (m *MsgRes) String() string            { return proto1.CompactTextString(m) }
func (*MsgRes) ProtoMessage()               {}
func (*MsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgRes) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto1.RegisterType((*MsgReq)(nil), "proto.MsgReq")
	proto1.RegisterType((*MsgRes)(nil), "proto.MsgRes")
	proto1.RegisterEnum("proto.MsgReq_MsgType", MsgReq_MsgType_name, MsgReq_MsgType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MsgGRPC service

type MsgGRPCClient interface {
	Chat(ctx context.Context, in *MsgReq, opts ...grpc.CallOption) (*MsgRes, error)
}

type msgGRPCClient struct {
	cc *grpc.ClientConn
}

func NewMsgGRPCClient(cc *grpc.ClientConn) MsgGRPCClient {
	return &msgGRPCClient{cc}
}

func (c *msgGRPCClient) Chat(ctx context.Context, in *MsgReq, opts ...grpc.CallOption) (*MsgRes, error) {
	out := new(MsgRes)
	err := grpc.Invoke(ctx, "/proto.MsgGRPC/Chat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MsgGRPC service

type MsgGRPCServer interface {
	Chat(context.Context, *MsgReq) (*MsgRes, error)
}

func RegisterMsgGRPCServer(s *grpc.Server, srv MsgGRPCServer) {
	s.RegisterService(&_MsgGRPC_serviceDesc, srv)
}

func _MsgGRPC_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgGRPCServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MsgGRPC/Chat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgGRPCServer).Chat(ctx, req.(*MsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MsgGRPC",
	HandlerType: (*MsgGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _MsgGRPC_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}

func init() { proto1.RegisterFile("network.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4b, 0x2d, 0x29,
	0xcf, 0x2f, 0xca, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4e, 0x5c,
	0x6c, 0xbe, 0xc5, 0xe9, 0x41, 0xa9, 0x85, 0x42, 0x02, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20, 0xa6, 0x92, 0x1a, 0x17, 0xbb, 0x6f, 0x71, 0x7a, 0x48, 0x65,
	0x41, 0xaa, 0x10, 0x2f, 0x17, 0x67, 0xa8, 0x9f, 0x8b, 0xab, 0x9b, 0xa7, 0x9f, 0xab, 0x8b, 0x00,
	0x83, 0x10, 0x0f, 0x17, 0x87, 0xbb, 0x6b, 0x88, 0x93, 0x8f, 0xbf, 0xb3, 0xb7, 0x00, 0xa3, 0x92,
	0x14, 0xd4, 0x8c, 0x62, 0x4c, 0x33, 0x8c, 0x0c, 0xc1, 0x66, 0xb8, 0x07, 0x05, 0x38, 0x0b, 0xa9,
	0x71, 0xb1, 0x38, 0x67, 0x24, 0x96, 0x08, 0xf1, 0x42, 0x5c, 0xa0, 0x07, 0xb1, 0x57, 0x0a, 0x85,
	0x5b, 0xac, 0xc4, 0xe0, 0x24, 0x1e, 0x25, 0xea, 0xe1, 0xe7, 0xa4, 0x9f, 0x98, 0x9c, 0x9c, 0x5a,
	0x5c, 0xac, 0x9f, 0x5e, 0x54, 0x90, 0xac, 0x0f, 0x56, 0x91, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x45, 0x6c, 0x14, 0x8b, 0xca, 0x00, 0x00, 0x00,
}
